<a href="https://colab.research.google.com/github/azhargies/CV/blob/CV/9_jan_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/Celsius_to_Fahrenheit.csv")

In [3]:
data.head()

   Celsius  Fahrenheit
0      -50       -58.0
1      -40       -40.0
2      -30       -22.0
3      -20        -4.0
4      -10        14.0

In [4]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(data["Celsius"], data["Fahrenheit"],test_size = 0.2, random_state=2)

In [5]:
xtrain.head()

23     9
6     -8
3    -20
20     6
5     -9
Name: Celsius, dtype: int64

In [6]:
from tensorflow import keras

In [17]:
model = keras.Sequential()
model.add(keras.layers.Dense(units=1, input_shape=[1]))
model.summary()
model.compile(optimizer = "Adam", loss = "mean_squared_error", metrics = ["mean_squared_error"])
model.fit(data["Celsius"], data["Fahrenheit"],epochs = 100)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 1)                 2

=================================================================
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 331ms/step - loss: 1048.2283 - mean_squared_error: 1048.2283
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 1047.9087 - mean_squared_error: 1047.9087
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 1047.5900 - mean_squared_error: 1047.5900
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 1047.2723 - mean_squared_error: 1047.2723
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 1046.9559 - mean_squared_error: 1046.9559
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 1046.6405 - mean_squared_error: 1046.6405
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 1046.3263 - mean_squared_error: 1046.3263
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 1046.0131 - mean_squared_error: 1046.0131
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 1045.7010 - mean_squared_error: 1045.7010
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 1045.3901 - mean_squared_error: 1045.3901
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 1045.0806 - mean_squared_error: 1045.0806
Epoch 12/100
1/1 [==============================] - 0s 9ms/step - loss: 1044.7721 - mean_squared_error: 1044.7721
Epoch 13/100
1/1 [==============================] - 0s 10ms/step - loss: 1044.4647 - mean_squared_error: 1044.4647
Epoch 14/100
1/1 [==============================] - 0s 8ms/step - loss: 1044.1587 - mean_squared_error: 1044.1587
Epoch 15/100
1/1 [==============================] - 0s 12ms/step - loss: 1043.8539 - mean_squared_error: 1043.8539
Epoch 16/100
1/1 [==============================] - 0s 8ms/step - loss: 1043.5503 - mean_squared_error: 1043.5503
Epoch 17/100
1/1 [==============================] - 0s 11ms/step - loss: 1043.2482 - mean_squared_error: 1043.2482
Epoch 18/100
1/1 [==============================] - 0s 9ms/step - loss: 1042.9470 - mean_squared_error: 1042.9470
Epoch 19/100
1/1 [==============================] - 0s 10ms/step - loss: 1042.6473 - mean_squared_error: 1042.6473
Epoch 20/100
1/1 [==============================] - 0s 10ms/step - loss: 1042.3489 - mean_squared_error: 1042.3489
Epoch 21/100
1/1 [==============================] - 0s 8ms/step - loss: 1042.0516 - mean_squared_error: 1042.0516
Epoch 22/100
1/1 [==============================] - 0s 13ms/step - loss: 1041.7557 - mean_squared_error: 1041.7557
Epoch 23/100
1/1 [==============================] - 0s 9ms/step - loss: 1041.4612 - mean_squared_error: 1041.4612
Epoch 24/100
1/1 [==============================] - 0s 24ms/step - loss: 1041.1681 - mean_squared_error: 1041.1681
Epoch 25/100
1/1 [==============================] - 0s 12ms/step - loss: 1040.8762 - mean_squared_error: 1040.8762
Epoch 26/100
1/1 [==============================] - 0s 7ms/step - loss: 1040.5856 - mean_squared_error: 1040.5856
Epoch 27/100
1/1 [==============================] - 0s 7ms/step - loss: 1040.2963 - mean_squared_error: 1040.2963
Epoch 28/100
1/1 [==============================] - 0s 8ms/step - loss: 1040.0084 - mean_squared_error: 1040.0084
Epoch 29/100
1/1 [==============================] - 0s 17ms/step - loss: 1039.7219 - mean_squared_error: 1039.7219
Epoch 30/100
1/1 [==============================] - 0s 9ms/step - loss: 1039.4368 - mean_squared_error: 1039.4368
Epoch 31/100
1/1 [==============================] - 0s 8ms/step - loss: 1039.1528 - mean_squared_error: 1039.1528
Epoch 32/100
1/1 [==============================] - 0s 11ms/step - loss: 1038.8704 - mean_squared_error: 1038.8704
Epoch 33/100
1/1 [==============================] - 0s 10ms/step - loss: 1038.5892 - mean_squared_error: 1038.5892
Epoch 34/100
1/1 [==============================] - 0s 7ms/step - loss: 1038.3094 - mean_squared_error: 1038.3094
Epoch 35/100
1/1 [==============================] - 0s 8ms/step - loss: 1038.0310 - mean_squared_error: 1038.0310
Epoch 36/100
1/1 [==============================] - 0s 7ms/step - loss: 1037.7539 - mean_squared_error: 1037.7539
Epoch 37/100
1/1 [==============================] - 0s 7ms/step - loss: 1037.4781 - mean_squared_error: 1037.4781
Epoch 38/100
1/1 [==============================] - 0s 7ms/step - loss: 1037.2039 - mean_squared_error: 1037.2039
Epoch 39/100
1/1 [==============================] - 0s 11ms/step - loss: 1036.9309 - mean_squared_error: 1036.9309
Epoch 40/100
1/1 [==============================] - 0s 6ms/step - loss: 1036.6593 - mean_squared_error: 1036.6593
Epoch 41/100
1/1 [==============================] - 0s 6ms/step - loss: 1036.3892 - mean_squared_error: 1036.3892
Epoch 42/100
1/1 [==============================] - 0s 7ms/step - loss: 1036.1202 - mean_squared_error: 1036.1202
Epoch 43/100
1/1 [==============================] - 0s 7ms/step - loss: 1035.8528 - mean_squared_error: 1035.8528
Epoch 44/100
1/1 [==============================] - 0s 6ms/step - loss: 1035.5864 - mean_squared_error: 1035.5864
Epoch 45/100
1/1 [==============================] - 0s 12ms/step - loss: 1035.3217 - mean_squared_error: 1035.3217
Epoch 46/100
1/1 [==============================] - 0s 7ms/step - loss: 1035.0582 - mean_squared_error: 1035.0582
Epoch 47/100
1/1 [==============================] - 0s 7ms/step - loss: 1034.7961 - mean_squared_error: 1034.7961
Epoch 48/100
1/1 [==============================] - 0s 10ms/step - loss: 1034.5354 - mean_squared_error: 1034.5354
Epoch 49/100
1/1 [==============================] - 0s 6ms/step - loss: 1034.2759 - mean_squared_error: 1034.2759
Epoch 50/100
1/1 [==============================] - 0s 6ms/step - loss: 1034.0177 - mean_squared_error: 1034.0177
Epoch 51/100
1/1 [==============================] - 0s 7ms/step - loss: 1033.7610 - mean_squared_error: 1033.7610
Epoch 52/100
1/1 [==============================] - 0s 8ms/step - loss: 1033.5056 - mean_squared_error: 1033.5056
Epoch 53/100
1/1 [==============================] - 0s 8ms/step - loss: 1033.2515 - mean_squared_error: 1033.2515
Epoch 54/100
1/1 [==============================] - 0s 6ms/step - loss: 1032.9987 - mean_squared_error: 1032.9987
Epoch 55/100
1/1 [==============================] - 0s 8ms/step - loss: 1032.7473 - mean_squared_error: 1032.7473
Epoch 56/100
1/1 [==============================] - 0s 6ms/step - loss: 1032.4972 - mean_squared_error: 1032.4972
Epoch 57/100
1/1 [==============================] - 0s 7ms/step - loss: 1032.2484 - mean_squared_error: 1032.2484
Epoch 58/100
1/1 [==============================] - 0s 11ms/step - loss: 1032.0007 - mean_squared_error: 1032.0007
Epoch 59/100
1/1 [==============================] - 0s 13ms/step - loss: 1031.7545 - mean_squared_error: 1031.7545
Epoch 60/100
1/1 [==============================] - 0s 8ms/step - loss: 1031.5096 - mean_squared_error: 1031.5096
Epoch 61/100
1/1 [==============================] - 0s 8ms/step - loss: 1031.2660 - mean_squared_error: 1031.2660
Epoch 62/100
1/1 [==============================] - 0s 8ms/step - loss: 1031.0237 - mean_squared_error: 1031.0237
Epoch 63/100
1/1 [==============================] - 0s 6ms/step - loss: 1030.7827 - mean_squared_error: 1030.7827
Epoch 64/100
1/1 [==============================] - 0s 8ms/step - loss: 1030.5428 - mean_squared_error: 1030.5428
Epoch 65/100
1/1 [==============================] - 0s 9ms/step - loss: 1030.3044 - mean_squared_error: 1030.3044
Epoch 66/100
1/1 [==============================] - 0s 7ms/step - loss: 1030.0671 - mean_squared_error: 1030.0671
Epoch 67/100
1/1 [==============================] - 0s 8ms/step - loss: 1029.8313 - mean_squared_error: 1029.8313
Epoch 68/100
1/1 [==============================] - 0s 7ms/step - loss: 1029.5964 - mean_squared_error: 1029.5964
Epoch 69/100
1/1 [==============================] - 0s 8ms/step - loss: 1029.3630 - mean_squared_error: 1029.3630
Epoch 70/100
1/1 [==============================] - 0s 8ms/step - loss: 1029.1307 - mean_squared_error: 1029.1307
Epoch 71/100
1/1 [==============================] - 0s 6ms/step - loss: 1028.8998 - mean_squared_error: 1028.8998
Epoch 72/100
1/1 [==============================] - 0s 9ms/step - loss: 1028.6702 - mean_squared_error: 1028.6702
Epoch 73/100
1/1 [==============================] - 0s 6ms/step - loss: 1028.4417 - mean_squared_error: 1028.4417
Epoch 74/100
1/1 [==============================] - 0s 6ms/step - loss: 1028.2144 - mean_squared_error: 1028.2144
Epoch 75/100
1/1 [==============================] - 0s 6ms/step - loss: 1027.9882 - mean_squared_error: 1027.9882
Epoch 76/100
1/1 [==============================] - 0s 7ms/step - loss: 1027.7634 - mean_squared_error: 1027.7634
Epoch 77/100
1/1 [==============================] - 0s 8ms/step - loss: 1027.5398 - mean_squared_error: 1027.5398
Epoch 78/100
1/1 [==============================] - 0s 7ms/step - loss: 1027.3174 - mean_squared_error: 1027.3174
Epoch 79/100
1/1 [==============================] - 0s 8ms/step - loss: 1027.0962 - mean_squared_error: 1027.0962
Epoch 80/100
1/1 [==============================] - 0s 10ms/step - loss: 1026.8762 - mean_squared_error: 1026.8762
Epoch 81/100
1/1 [==============================] - 0s 7ms/step - loss: 1026.6573 - mean_squared_error: 1026.6573
Epoch 82/100
1/1 [==============================] - 0s 8ms/step - loss: 1026.4397 - mean_squared_error: 1026.4397
Epoch 83/100
1/1 [==============================] - 0s 6ms/step - loss: 1026.2231 - mean_squared_error: 1026.2231
Epoch 84/100
1/1 [==============================] - 0s 9ms/step - loss: 1026.0079 - mean_squared_error: 1026.0079
Epoch 85/100
1/1 [==============================] - 0s 6ms/step - loss: 1025.7936 - mean_squared_error: 1025.7936
Epoch 86/100
1/1 [==============================] - 0s 6ms/step - loss: 1025.5807 - mean_squared_error: 1025.5807
Epoch 87/100
1/1 [==============================] - 0s 8ms/step - loss: 1025.3689 - mean_squared_error: 1025.3689
Epoch 88/100
1/1 [==============================] - 0s 7ms/step - loss: 1025.1582 - mean_squared_error: 1025.1582
Epoch 89/100
1/1 [==============================] - 0s 7ms/step - loss: 1024.9487 - mean_squared_error: 1024.9487
Epoch 90/100
1/1 [==============================] - 0s 8ms/step - loss: 1024.7404 - mean_squared_error: 1024.7404
Epoch 91/100
1/1 [==============================] - 0s 6ms/step - loss: 1024.5330 - mean_squared_error: 1024.5330
Epoch 92/100
1/1 [==============================] - 0s 7ms/step - loss: 1024.3268 - mean_squared_error: 1024.3268
Epoch 93/100
1/1 [==============================] - 0s 9ms/step - loss: 1024.1218 - mean_squared_error: 1024.1218
Epoch 94/100
1/1 [==============================] - 0s 7ms/step - loss: 1023.9180 - mean_squared_error: 1023.9180
Epoch 95/100
1/1 [==============================] - 0s 10ms/step - loss: 1023.7151 - mean_squared_error: 1023.7151
Epoch 96/100
1/1 [==============================] - 0s 6ms/step - loss: 1023.5134 - mean_squared_error: 1023.5134
Epoch 97/100
1/1 [==============================] - 0s 6ms/step - loss: 1023.3127 - mean_squared_error: 1023.3127
Epoch 98/100
1/1 [==============================] - 0s 6ms/step - loss: 1023.1133 - mean_squared_error: 1023.1133
Epoch 99/100
1/1 [==============================] - 0s 6ms/step - loss: 1022.9149 - mean_squared_error: 1022.9149
Epoch 100/100
1/1 [==============================] - 0s 6ms/step - loss: 1022.7176 - mean_squared_error: 1022.7176

In [21]:
model.predict([255])

1/1 [==============================] - 0s 40ms/step

array([[450.4634]], dtype=float32)

In [23]:
model.intercept

AttributeError: ignored

In [28]:
abalone_train = pd.read_csv(
    "https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",
    names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight",
           "Viscera weight", "Shell weight", "Age"])

abalone_train.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Age
0,0.435,0.335,0.110,0.334,0.1355,0.0775,0.0965,7
1,0.585,0.450,0.125,0.874,0.3545,0.2075,0.2250,6
2,0.655,0.510,0.160,1.092,0.3960,0.2825,0.3700,14
3,0.545,0.425,0.125,0.768,0.2940,0.1495,0.2600,16
4,0.545,0.420,0.130,0.879,0.3740,0.1695,0.2300,13

In [32]:
abalone_features = abalone_train.copy()
abalone_features.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Age
0,0.435,0.335,0.110,0.334,0.1355,0.0775,0.0965,7
1,0.585,0.450,0.125,0.874,0.3545,0.2075,0.2250,6
2,0.655,0.510,0.160,1.092,0.3960,0.2825,0.3700,14
3,0.545,0.425,0.125,0.768,0.2940,0.1495,0.2600,16
4,0.545,0.420,0.130,0.879,0.3740,0.1695,0.2300,13

In [33]:
abalone_features.pop('Age')

0        7
1        6
2       14
3       16
4       13
        ..
3315    15
3316    10
3317    11
3318    16
3319    19
Name: Age, Length: 3320, dtype: int64

In [34]:
abalone_features.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
0,0.435,0.335,0.110,0.334,0.1355,0.0775,0.0965
1,0.585,0.450,0.125,0.874,0.3545,0.2075,0.2250
2,0.655,0.510,0.160,1.092,0.3960,0.2825,0.3700
3,0.545,0.425,0.125,0.768,0.2940,0.1495,0.2600
4,0.545,0.420,0.130,0.879,0.3740,0.1695,0.2300

In [35]:
abalone_features = np.array(abalone_features)
abalone_features

array([[0.435 , 0.335 , 0.11  , ..., 0.1355, 0.0775, 0.0965],
       [0.585 , 0.45  , 0.125 , ..., 0.3545, 0.2075, 0.225 ],
       [0.655 , 0.51  , 0.16  , ..., 0.396 , 0.2825, 0.37  ],
       ...,
       [0.53  , 0.42  , 0.13  , ..., 0.3745, 0.167 , 0.249 ],
       [0.395 , 0.315 , 0.105 , ..., 0.1185, 0.091 , 0.1195],
       [0.45  , 0.355 , 0.12  , ..., 0.1145, 0.0665, 0.16  ]])

In [38]:
abalone_features.shape

(3320, 7)

In [45]:
abalone_model = tf.keras.Sequential([
  keras.layers.Dense(units = 16, input_shape = (7,)),
  keras.layers.Dense(1)
])

abalone_model.compile(loss = tf.keras.losses.MeanSquaredError(),
                      optimizer = tf.keras.optimizers.Adam())

In [46]:
abalone_model.fit(abalone_features, abalone_labels, epochs=50)

Epoch 1/50
104/104 [==============================] - 1s 3ms/step - loss: 79.2762
Epoch 2/50
104/104 [==============================] - 0s 2ms/step - loss: 34.3736
Epoch 3/50
104/104 [==============================] - 0s 2ms/step - loss: 11.8203
Epoch 4/50
104/104 [==============================] - 0s 3ms/step - loss: 8.4400
Epoch 5/50
104/104 [==============================] - 0s 2ms/step - loss: 8.1727
Epoch 6/50
104/104 [==============================] - 0s 2ms/step - loss: 8.0097
Epoch 7/50
104/104 [==============================] - 0s 3ms/step - loss: 7.8583
Epoch 8/50
104/104 [==============================] - 0s 2ms/step - loss: 7.7066
Epoch 9/50
104/104 [==============================] - 0s 2ms/step - loss: 7.5711
Epoch 10/50
104/104 [==============================] - 0s 2ms/step - loss: 7.4517
Epoch 11/50
104/104 [==============================] - 0s 3ms/step - loss: 7.3450
Epoch 12/50
104/104 [==============================] - 0s 2ms/step - loss: 7.2514
Epoch 13/50
104/104 [==============================] - 0s 2ms/step - loss: 7.1682
Epoch 14/50
104/104 [==============================] - 0s 2ms/step - loss: 7.0920
Epoch 15/50
104/104 [==============================] - 0s 2ms/step - loss: 7.0207
Epoch 16/50
104/104 [==============================] - 0s 2ms/step - loss: 6.9652
Epoch 17/50
104/104 [==============================] - 0s 2ms/step - loss: 6.9026
Epoch 18/50
104/104 [==============================] - 0s 2ms/step - loss: 6.8529
Epoch 19/50
104/104 [==============================] - 0s 2ms/step - loss: 6.7953
Epoch 20/50
104/104 [==============================] - 0s 2ms/step - loss: 6.7532
Epoch 21/50
104/104 [==============================] - 0s 2ms/step - loss: 6.7050
Epoch 22/50
104/104 [==============================] - 0s 2ms/step - loss: 6.6457
Epoch 23/50
104/104 [==============================] - 0s 2ms/step - loss: 6.5929
Epoch 24/50
104/104 [==============================] - 0s 2ms/step - loss: 6.5519
Epoch 25/50
104/104 [==============================] - 0s 2ms/step - loss: 6.4987
Epoch 26/50
104/104 [==============================] - 0s 2ms/step - loss: 6.4484
Epoch 27/50
104/104 [==============================] - 0s 2ms/step - loss: 6.3915
Epoch 28/50
104/104 [==============================] - 0s 2ms/step - loss: 6.3413
Epoch 29/50
104/104 [==============================] - 0s 2ms/step - loss: 6.2871
Epoch 30/50
104/104 [==============================] - 0s 2ms/step - loss: 6.2368
Epoch 31/50
104/104 [==============================] - 0s 2ms/step - loss: 6.1898
Epoch 32/50
104/104 [==============================] - 0s 2ms/step - loss: 6.1237
Epoch 33/50
104/104 [==============================] - 0s 2ms/step - loss: 6.0751
Epoch 34/50
104/104 [==============================] - 0s 2ms/step - loss: 6.0195
Epoch 35/50
104/104 [==============================] - 0s 2ms/step - loss: 5.9656
Epoch 36/50
104/104 [==============================] - 0s 2ms/step - loss: 5.9086
Epoch 37/50
104/104 [==============================] - 0s 2ms/step - loss: 5.8578
Epoch 38/50
104/104 [==============================] - 0s 2ms/step - loss: 5.8233
Epoch 39/50
104/104 [==============================] - 0s 2ms/step - loss: 5.7600
Epoch 40/50
104/104 [==============================] - 0s 2ms/step - loss: 5.7019
Epoch 41/50
104/104 [==============================] - 0s 2ms/step - loss: 5.6495
Epoch 42/50
104/104 [==============================] - 0s 2ms/step - loss: 5.6010
Epoch 43/50
104/104 [==============================] - 0s 2ms/step - loss: 5.5541
Epoch 44/50
104/104 [==============================] - 0s 2ms/step - loss: 5.5076
Epoch 45/50
104/104 [==============================] - 0s 2ms/step - loss: 5.4613
Epoch 46/50
104/104 [==============================] - 0s 2ms/step - loss: 5.4099
Epoch 47/50
104/104 [==============================] - 0s 2ms/step - loss: 5.3623
Epoch 48/50
104/104 [==============================] - 0s 2ms/step - loss: 5.3473
Epoch 49/50
104/104 [==============================] - 0s 2ms/step - loss: 5.3067
Epoch 50/50
104/104 [==============================] - 0s 2ms/step - loss: 5.2649